### ISSUE TITLE
issue with importing react-virtualized

### ISSUE THREAD

**Issue by deepshikha02** [wangtao0101/react-virtualized-transfer#3]
Hi,
I am trying to use the react-virtualized module in a project. 
Things work fine but the moment I try to import the styles file. I get an unexpected token error. 
import 'react-virtualized/styles.css';

ERROR in ./node_modules/react-virtualized/styles.css 3:0
Module parse failed: Unexpected token (3:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /* Collection default theme */
| 
> .ReactVirtualized__Collection {
| }

I really need some help here. 

Thanks
Deeps

**Comment by wangtao0101** [comment]
You should use [css-loader](https://github.com/webpack-contrib/css-loader) to handle css files.

**Comment by marisev** [comment]
@deepshikha02 were you able to solve this? I’m running into the same issue :(
